
module.exports = Object.freeze({
    MODAL_BODY_TYPES: {
        USER_DETAIL: "USER_DETAIL",
        LEAD_ADD_NEW: "LEAD_ADD_NEW",
        CONFIRMATION: "CONFIRMATION",
        PROVINCE_ADD_NEW: "PROVINCE_ADD_NEW",
        DISTRICT_ADD_NEW: "DISTRICT_ADD_NEW",
        COMMUNE_ADD_NEW: "COMMUNE_ADD_NEW",
        MEMBER_ADD_NEW: "MEMBER_ADD_NEW",
        MEMBER_ADD_ORGANIZATION: "MEMBER_ADD_ORGANIZATION",
        DEFAULT: "",

    },

    RIGHT_DRAWER_TYPES: {
        NOTIFICATION: "NOTIFICATION",
        CALENDAR_EVENTS: "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES: {
        LEAD_DELETE: "LEAD_DELETE",
        ORGANIZATION_DELETE: "ORGANIZATION_DELETE",
        MEMBER_DELETE: "MEMBER_DELETE",
        MEMBER_OUT_ORGANIZATION: "MEMBER_OUT_ORGANIZATION"
    },
    ORGANIZATION_TYPE: {
        PROVINCE: "province",
        DISTRICT: "district",
        COMMUNE: "commune"
    }
});
